= Урок 3: Работа с LiveData в Тестах: InstantExecutorExtension
:author: Пархейчук Дмитрий Александрович
:email: d.parkheichuk@yandex.ru
:revnumber: 1.0
:revdate: 2025-10-30
:doctype: article
:encoding: utf-8
:lang: ru
:sectnums:

[[section-livedata-challenge]]
== Проблема LiveData в Тестах

Многие DAO-методы в Android Room возвращают `LiveData` для реактивного получения данных. `LiveData` по своей природе асинхронна и обычно обновляется в основном потоке. В тестах это может вызвать проблемы:

*   Тесты могут завершиться раньше, чем `LiveData` успеет обновить свое значение.
*   Необходимость управлять потоками усложняет написание тестов.

Для решения этой проблемы в JUnit 4 использовалось `InstantTaskExecutorRule`. В JUnit 5 мы можем создать аналогичное поведение с помощью кастомного расширения.

[[section-instant-executor-extension]]
== InstantExecutorExtension для JUnit 5

Это расширение перехватывает выполнение задач `LiveData` и заставляет их выполняться синхронно, немедленно, в том же потоке, где запущен тест.

Код `InstantExecutorExtension` остается на Java, так как он работает с низкоуровневыми компонентами Android Architecture. В Kotlin-проекте он будет работать без изменений. Подробное описание его работы есть в уроке 3.1.

```java
// d:/t366/code/sdet-practice/kotlin-android-test-demo/app/src/androidTest/java/com/example/app/utils/InstantExecutorExtension.java
package com.example.app.utils; // Замените на ваш пакет

import androidx.arch.core.executor.ArchTaskExecutor;
import androidx.arch.core.executor.TaskExecutor;
import org.junit.jupiter.api.extension.AfterEachCallback;
import org.junit.jupiter.api.extension.BeforeEachCallback;
import org.junit.jupiter.api.extension.ExtensionContext;

public class InstantExecutorExtension implements BeforeEachCallback, AfterEachCallback {
    // ... (код расширения, как в уроке 3.1)
}
```

=== Как использовать `InstantExecutorExtension`

Чтобы применить это расширение к вашим тестовым классам, используйте аннотацию `@ExtendWith`:

```kotlin
import org.junit.jupiter.api.extension.ExtendWith

@ExtendWith(InstantExecutorExtension::class)
class AppDaoTest : BaseDaoTest() {
    // ... ваши тесты
}
```

В следующем уроке мы создадим более идиоматичные утилиты для тестирования `LiveData` с использованием расширений Kotlin.