# Глобальные настройки по умолчанию для всех jobs
default:
  image: $CI_REGISTRY_IMAGE/android-builder:latest
  tags:
    - docker

# Переменные, доступные во всех jobs. Указываем Gradle, где хранить кэш.
variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

# Определяем два типа кэша: один для зависимостей, другой для сборочного кэша.
cache:
  - key:
      files:
        - build.gradle # Ключ для зависимостей
    paths:
      - $GRADLE_USER_HOME/caches/modules-2
      - $GRADLE_USER_HOME/caches/jars-9
    policy: pull # Зависимости только загружаем, не перезаписываем в каждой job
  - key: "gradle-build-cache-${CI_COMMIT_REF_SLUG}" # Ключ для сборочного кэша
    paths:
      - $GRADLE_USER_HOME/caches/build-cache-8
    policy: pull-push # Сборочный кэш обновляем

stages:
  - .pre
  - analyse
  - module_tests
  - build
  - integration_tests
  - system_tests
  - performance_tests
  - report
  - publish
  - deploy

prepare_dependencies:
  stage: .pre
  script:
    - ./gradlew androidDependencies
  cache:
    # На этой стадии мы только создаем/обновляем кэш, но ничего не загружаем
    - key:
        files:
          - build.gradle
      paths:
        - $GRADLE_USER_HOME/caches/modules-2
        - $GRADLE_USER_HOME/caches/jars-9
      policy: push # Только выгружаем обновленные зависимости
    - key: "gradle-build-cache-${CI_COMMIT_REF_SLUG}"
      paths:
        - $GRADLE_USER_HOME/caches/build-cache-8
      policy: push

pmd:
  stage: analyse
  script:
    - ./gradlew app:pmdDebug
  artifacts:
    when: always
    paths:
      - app/build/reports/pmd/debug.html
    expire_in: 1 day # Храним артефакт 1 день

checkstyle:
  stage: analyse
  script:
    - ./gradlew app:checkstyleDebug
  artifacts:
    when: always
    paths:
      - app/build/reports/checkstyle/debug.html
    expire_in: 1 day

android_lint:
  stage: analyse
  script:
    - ./gradlew app:lintDebug
  artifacts:
    when: always
    paths:
      - app/build/reports/lint-results-debug.html
    expire_in: 1 day

unit_tests:
  stage: module_tests
  # needs: ["prepare_dependencies", "android_lint", "pmd", "checkstyle"] # Закомментировано для ускорения отладки
  script:
    - ./gradlew testDebugUnitTest
  artifacts:
    when: always
    paths:
      - app/build/reports/tests/testDebugUnitTest/
    expire_in: 1 day

ui_module_tests:
  stage: module_tests
  script: "echo 'Module tests...'"

build:
  stage: build
  needs: ["unit_tests"]
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/debug/
    expire_in: 7 days

ui_integration_tests:
  stage: integration_tests
  script: "echo 'Integration tests...'"

api_integration_tests:
  stage: integration_tests
  script: "echo 'API tests...'"

snapshot_tests:
  stage: integration_tests
  script: "echo 'Snapshot tests...'"

instrumental_tests:
  stage: system_tests
  script: "echo 'Instrumental tests...'"

ui_e2e_tests:
  stage: system_tests
  script: "echo 'System tests...'"

# Job для публикации отчетов на GitLab Pages
pages:
  stage: publish
  # Запускается только для ветки develop
  rules:
    # - if: '$CI_COMMIT_BRANCH == "main"'
  needs:
    - job: pmd
      artifacts: true
    - job: checkstyle
      artifacts: true
    - job: android_lint
      artifacts: true
    - job: unit_tests
      artifacts: true
  when: always
  script:
    - echo "Собираем отчеты для публикации на GitLab Pages..."
    - mkdir -p public

    # Создаем поддиректории для каждого отчета
    - mkdir -p public/checkstyle public/pmd public/lint public/unit-tests

    # Копируем отчеты, проверяя их наличие
    - '[ -d app/build/reports/checkstyle ] && cp -r app/build/reports/checkstyle/* public/checkstyle/'
    - '[ -d app/build/reports/pmd ] && cp -r app/build/reports/pmd/* public/pmd/'
    - '[ -f app/build/reports/lint-results-debug.html ] && cp app/build/reports/lint-results-debug.html public/lint/index.html'
    - '[ -d app/build/reports/tests/testDebugUnitTest ] && cp -r app/build/reports/tests/testDebugUnitTest/* public/unit-tests/'

    # Создаем главную страницу со ссылками
    - |
      echo "<html><head><title>Отчеты о сборке</title></head><body><h1>Отчеты о сборке</h1><ul>" > public/index.html
      echo '<li><a href="checkstyle/debug.html">Отчет Checkstyle</a></li>' >> public/index.html
      echo '<li><a href="pmd/debug.html">Отчет PMD</a></li>' >> public/index.html
      echo '<li><a href="lint/index.html">Отчет Android Lint</a></li>' >> public/index.html
      echo '<li><a href="unit-tests/index.html">Отчет Unit-тестов</a></li>' >> public/index.html
      echo "</ul></body></html>" >> public/index.html
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  needs: ["pages"]
  when: manual
  script: "echo 'Deploy...'"