stages:
  - analyse_code
  - module_tests
  - build
  - integration_tests
  - system_tests
  - performance_tests
  - deploy
  - report

pmd:
  stage: analyse_code
  script: "echo 'PMD analysis...'"

checkstyle:
  stage: analyse_code
  script: "echo 'Checkstyle analysis...'"

android_lint:
  stage: analyse_code
  script: "echo 'Android Lint analysis...'"

unit_tests:
  stage: module_tests
  script: "echo 'Unit tests...'"

ui_module_tests:
  stage: module_tests
  script: "echo 'Module tests...'"

build:
  stage: build
  script: "echo 'Build...'"

ui_integration_tests:
  stage: integration_tests
  script: "echo 'Integration tests...'"

api_integration_tests:
  stage: integration_tests
  script: "echo 'API tests...'"

snapshot_tests:
  stage: integration_tests
  script: "echo 'Snapshot tests...'"

instrumental_tests:
  stage: system_tests
  script: "echo 'Instrumental tests...'"

ui_e2e_tests:
  stage: system_tests
  script: "echo 'System tests...'"

deploy:
  stage: deploy
  script: "echo 'Deploy...'"

publish_report:
  stage: deploy
  script: "echo 'Publish report'"

report: 
  stage: report
  script: "echo 'Deploy report...'"