// Top-level build file for plugins.
// Apply false means the plugin is available for sub-projects but not applied to the root project.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.kotlin.android) apply false
    alias(libs.plugins.google.services) apply false
    alias(libs.plugins.firebase.crashlytics) apply false
    alias(libs.plugins.allure) apply false
    alias(libs.plugins.junit5) apply false
}
