pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://www.jitpack.io" }
    }
}
dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        maven { url "https://www.jitpack.io" }
    }
}
rootProject.name='SDET ANDROID DEMO'
include ':app'
