Урок 6: Обработка Исключений (`TestExecutionExceptionHandler`)
:author: Пархейчук Дмитрий Александрович
:email: d.parkheichuk@yandex.ru
:revnumber: 1.0
:revdate: 2025-11-19
:doctype: article
:encoding: utf-8
:lang: ru
:sectnums:

[[section-what-is-teeh]]
== Что такое `TestExecutionExceptionHandler`?

Этот интерфейс расширения позволяет перехватывать исключения, которые были выброшены во время выполнения теста (включая методы `@BeforeEach`, `@AfterEach` и сам `@Test`).

Это дает вам возможность:
*   "Проглотить" определенные типы исключений, чтобы тест не падал.
*   Выполнить какую-то дополнительную логику при возникновении исключения (например, сделать скриншот).
*   Заменить одно исключение другим.

[[section-example]]
== Пример: Игнорирование определенного исключения

Предположим, мы хотим, чтобы наши тесты не падали, если возникает `IOException`, а просто логировали это.

```kotlin
import org.junit.jupiter.api.extension.ExtensionContext
import org.junit.jupiter.api.extension.TestExecutionExceptionHandler
import java.io.IOException
import java.util.logging.Logger

class IgnoreIoExceptionExtension : TestExecutionExceptionHandler {

    companion object {
        private val logger = Logger.getLogger(IgnoreIoExceptionExtension::class.java.name)
    }

    override fun handleTestExecutionException(context: ExtensionContext, throwable: Throwable) {
        // Если это IOException, логируем его и "проглатываем"
        if (throwable is IOException) {
            logger.warning("Ignoring IOException: ${throwable.message}")
            return // Не выбрасываем исключение дальше
        }

        // Все остальные исключения выбрасываем дальше, чтобы тест упал
        throw throwable
    }
}

@ExtendWith(IgnoreIoExceptionExtension::class)
class MyExceptionTest {
    @Test
    fun `test that throws io exception`() {
        throw IOException("File not found, but we don't care")
    }
}
```

Этот тест будет помечен как успешно пройденный, так как наше расширение перехватило и "проглотило" `IOException`.