Урок 3: Пост-обработка Экземпляра Теста (`TestInstancePostProcessor`)
:author: Пархейчук Дмитрий Александрович
:email: d.parkheichuk@yandex.ru
:revnumber: 1.0
:revdate: 2025-11-19
:doctype: article
:encoding: utf-8
:lang: ru
:sectnums:

[[section-what-is-tipp]]
== Что такое `TestInstancePostProcessor`?

Этот интерфейс расширения предоставляет точку входа *сразу после создания экземпляра тестового класса*, но *до* выполнения любых методов (`@BeforeAll` или `@BeforeEach`).

Это делает его идеальным инструментом для реализации **внедрения зависимостей (Dependency Injection)**. Вы можете "проинспектировать" тестовый класс, найти поля, помеченные определенной аннотацией, и внедрить в них необходимые объекты (моки, сервисы и т.д.).

Именно так работают расширения `MockitoExtension` и `MockKExtension`.

[[section-example]]
== Пример: Простое внедрение зависимости

Давайте создадим аннотацию `@Inject` и расширение, которое будет внедрять объект `MyService` в поля, помеченные этой аннотацией.

```kotlin
// 1. Создаем аннотацию
@Target(AnnotationTarget.FIELD)
@Retention(AnnotationRetention.RUNTIME)
annotation class Inject

// 2. Создаем расширение
class MyServiceInjectorExtension : TestInstancePostProcessor {

    override fun postProcessTestInstance(testInstance: Any, context: ExtensionContext) {
        // Находим все поля в тестовом классе
        testInstance::class.java.declaredFields.forEach { field ->
            // Если поле помечено аннотацией @Inject и имеет тип MyService
            if (field.isAnnotationPresent(Inject::class.java) && field.type == MyService::class.java) {
                field.isAccessible = true // Делаем приватное поле доступным
                field.set(testInstance, MyService()) // Внедряем новый экземпляр сервиса
            }
        }
    }
}

// 3. Используем в тесте
@ExtendWith(MyServiceInjectorExtension::class)
class MyServiceTest {
    @Inject
    private lateinit var myService: MyService // Сюда будет внедрен объект

    @Test
    fun `service should not be null`() {
        assertThat(myService).isNotNull()
    }
}
```

Этот пример демонстрирует базовый принцип, на котором построены сложные DI-механизмы в тестовых фреймворках.