= Композитные Аннотации
:source-highlighter: highlight.js

:author: Пархейчук Дмитрий Александрович
:email: d.parkheichuk@yandex.ru
:revnumber: 1.0
:revdate: 2025-11-19
:doctype: article
:encoding: utf-8
:lang: ru
:sectnums:

[[section-what-is-ca]]
== Что такое Композитные Аннотации?

Когда вы используете несколько расширений одновременно, тестовый класс может стать "замусоренным" аннотациями:

```kotlin
@ExtendWith(MockitoExtension::class)
@ExtendWith(InstantExecutorExtension::class)
@ExtendWith(LoggingExtension::class)
@Tag("ViewModelTest")
class MyViewModelTest {
    // ...
}
```

JUnit 5 позволяет создавать **композитные аннотации**. Это ваши собственные аннотации, которые помечены другими аннотациями JUnit 5. Фреймворк автоматически "увидит" и применит все мета-аннотации.

[[section-example]]
== Пример: Создание аннотации `@ViewModelTest`

Давайте создадим одну аннотацию `@ViewModelTest`, которая заменит все четыре аннотации из примера выше.

```kotlin
import org.junit.jupiter.api.Tag
import org.junit.jupiter.api.extension.ExtendWith

@Target(AnnotationTarget.CLASS)
@Retention(AnnotationRetention.RUNTIME)
@ExtendWith(MockitoExtension::class, InstantExecutorExtension::class, LoggingExtension::class)
@Tag("ViewModelTest")
annotation class ViewModelTest

// Теперь наш тестовый класс выглядит намного чище:
@ViewModelTest
class MyViewModelTest {
    // ...
}
```

Использование композитных аннотаций — это мощный способ сделать ваши тесты более читаемыми, уменьшить количество шаблонного кода и создать свой собственный, предметно-ориентированный "диалект" для написания тестов.