name: 'Setup Android Environment'
description: 'Checks out code, sets up JDK 17, caches Gradle dependencies, and makes gradlew executable.'

runs:
  using: "composite"
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      shell: bash
      run: chmod +x gradlew
