= Урок 1: Глобальные переменные и кэш

На этом шаге мы добавим в `.gitlab-ci.yml` блок `variables`, чтобы определить переменные окружения, доступные во всех задачах (`jobs`). Это помогает сделать конфигурацию более чистой и предсказуемой.

== Зачем нужна переменная `GRADLE_USER_HOME`?

Мы определяем переменную `GRADLE_USER_HOME` и присваиваем ей значение `+$CI_PROJECT_DIR/.gradle+`.

`$CI_PROJECT_DIR` — это пред
определенная переменная GitLab, которая указывает на корневую директорию вашего проекта внутри Runner'а.

*   *Надежность:* Вместо того чтобы полагаться на домашнюю директорию пользователя по умолчанию (`~/.gradle`), мы явно указываем Gradle, где хранить свои кэши и другие файлы. Это делает пути к кэшу абсолютно предсказуемыми и устраняет потенциальные проблемы с правами доступа внутри Docker-контейнера.
*   *Централизация:* Все, что связано с Gradle, будет находиться внутри папки проекта, что упрощает управление артефактами и кэшем.

== Изменения в `.gitlab-ci.yml`

Мы добавляем блок `variables` в начало файла.

[source,gitlab-ci.yml]
----
tags:
   - docker
 
# Переменные, доступные во всех jobs. Указываем Gradle, где хранить кэш.
variables:
  GRADLE_USER_HOME: $CI_PROJECT_DIR/.gradle

# Определяем два типа кэша: один для зависимостей, другой для сборочного кэша.
cache:
   - key:
----