= Урок 5: Запуск Unit-тестов

Теперь добавим задачу `unit_tests` для запуска модульных тестов. Это критически важный этап проверки качества кода.

== Что делает эта задача?

*   *`stage: module_tests`*: Задача выполняется на своей собственной стадии после анализа кода.
*   *`needs: ["prepare_dependencies"]`*: Это важная оптимизация. Мы говорим, что для запуска `unit_tests` нужно дождаться завершения *только* задачи `prepare_dependencies`. Таким образом, тесты начнут выполняться, *не дожидаясь* окончания долгого статического анализа (`pmd`, `checkstyle`, `lint`). Это значительно сокращает общее время выполнения пайплайна.
*   *`script: - ./gradlew testDebugUnitTest`*: Стандартная команда для запуска JVM-тестов в Android-проекте.

Как и в предыдущем шаге, мы пока не сохраняем отчеты. Если хотя бы один тест упадет, задача завершится с ошибкой, и пайплайн остановится.

== Изменения в `.gitlab-ci.yml`

[source,diff]
----
unit_tests:
  stage: module_tests
  needs: ["prepare_dependencies"] # Запускаем тесты, не дожидаясь анализаторов
  script:
    - ./gradlew testDebugUnitTest
----