name: 'Cache Gradle Dependencies'
description: 'Caches and restores Gradle dependencies and wrapper.'

runs:
  using: "composite"
  steps:
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-