# .github/workflows/component-ui-test-flow.yml
name: Component UI

on:
  workflow_call:
    secrets:
      SAUCE_USERNAME:
        required: true
      SAUCE_ACCESS_KEY:
        required: true

jobs:
  run_component_ui_tests:
    name: UI components
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [26, 34]
        target: [google_apis]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Android Environment
        uses: ./.github/actions/setup-android
        with:
          java-version: '17'

      - name: Cache and Restore Gradle packages
        uses: ./.github/actions/cache-gradle

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run Component UI Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: pixel_7_pro
          script: ./gradlew connectedDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.tags=component-ui -Pqameta.allure.enabled=true

      - name: Upload HTML Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: component-ui-test-report-${{ matrix.api-level }}-${{ matrix.target }}
          path: |
            app/build/reports/androidTests/connected/

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-component-ui-${{ matrix.api-level }}-${{ matrix.target }}
          path: app/build/allure-results/