# .github/workflows/integration-ui-test-flow.yml
name: Integration UI Test Flow

on:
  workflow_call:
    secrets:
      SAUCE_USERNAME:
        required: true
      SAUCE_ACCESS_KEY:
        required: true

jobs:
  run_integration_ui_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Android Environment
        uses: ./.github/actions/setup-android
        with:
          java-version: '17'

      - name: Cache and Restore Gradle packages
        uses: ./.github/actions/cache-gradle

      - name: Run Integration UI Tests on Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          emulator-options: -no-window -no-snapshot -no-audio -no-boot-anim
          script: ./gradlew connectedDebugAndroidTest -Pandroid.testInstrumentationRunnerArguments.tags=integration-ui

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-ui-test-reports
          path: |
            app/build/allure-results/
            app/build/reports/androidTests/connected/
