name: INTEGRATION-TEST

on:
  workflow_call:

jobs:
  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Android Environment
        uses: ./.github/actions/setup-android

      - name: Restore Gradle cache
        uses: ./.github/actions/cache-gradle

      - name: Run integration tests
        run: ./gradlew testDebugUnitTest -Djunit.jupiter.tags.include=database

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: db-integration-test-report
          path: |
            app/build/reports/tests/testDebugUnitTest/
          retention-days: 2

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-db
          path: |
            app/build/allure-results/
          retention-days: 2